### ISSUE TITLE
About train_base.py

### ISSUE THREAD

**Issue by CUMTzackGit** [HaoZhongkai/AS_Molecule#1]
I encountered a problem. what can I do about it?

Traceback (most recent call last):
  File "train_base.py", line 145, in <module>
    train_set.load_mol(config.train_pkl[args.dataset]), test_set.load_mol(
  File "../utils/funcs.py", line 291, in load_mol
    self.mols.extend(pickle.load(open(path, 'rb')))
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/OPV/opv_mol_train1.pkl'

**Comment by geekinglcq** [comment]
First, you could download the OPV dataset, and then put them in the current fold `../datasets/OPV/`.

**Comment by HaoZhongkai** [comment]
Hello,
&nbsp; You need to download the OPV dataset from the link in the paper first. Then you can use the functions in "/utils/pre" to preprocess the dataset and save them in "/datasets/OPV/"




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HaoZhongkai/AS_Molecule"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月17日(星期六) 下午4:26
收件人:&nbsp;"HaoZhongkai/AS_Molecule"<AS_Molecule@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HaoZhongkai/AS_Molecule] About train_base.py (#1)





 
I encountered a problem. what can I do about it?
 
Traceback (most recent call last):
 File "train_base.py", line 145, in 
 train_set.load_mol(config.train_pkl[args.dataset]), test_set.load_mol(
 File "../utils/funcs.py", line 291, in load_mol
 self.mols.extend(pickle.load(open(path, 'rb')))
 FileNotFoundError: [Errno 2] No such file or directory: '../datasets/OPV/opv_mol_train1.pkl'
