### ISSUE TITLE
How to use the codes to reproduce results in the paper?

### ISSUE THREAD

**Issue by matouk98** [HaoZhongkai/AS_Molecule#2]
Thanks a lot for your great work! I am wondering about how to use the codes to reproduce results in the paper? Could you please provide some scripts? I am also confused about the pretraining folder, is every file useful? Where is the code for ASGN model?  Looking forward to your reply! Thanks again!!

**Comment by wangzeyu135798** [comment]
I have the same question, there are so many files!

**Comment by HaoZhongkai** [comment]
Hello,
&nbsp; &nbsp;The main files are in './single_model_al' , you can prepare dataset you want to run in the './dataset' folder. Other files are baselines or files for preprocessing.


best regards,


Zhongkai Hao




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HaoZhongkai/AS_Molecule"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 上午10:22
收件人:&nbsp;"HaoZhongkai/AS_Molecule"<AS_Molecule@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [HaoZhongkai/AS_Molecule] How to use the codes to reproduce results in the paper? (#2)





 
I have the same question, there are so many files!

**Comment by geekinglcq** [comment]
> Hello, &nbsp; &nbsp;The main files are in './single_model_al' , you can prepare dataset you want to run in the './dataset' folder. Other files are baselines or files for preprocessing. best regards, Zhongkai Hao
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HaoZhongkai/AS_Molecule" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月2日(星期一) 上午10:22 收件人:&nbsp;"HaoZhongkai/AS_Molecule"<AS_Molecule@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [HaoZhongkai/AS_Molecule] How to use the codes to reproduce results in the paper? (#2) I have the same question, there are so many files! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Maybe we could refactor these code this weekend later.
