### ISSUE TITLE
QM9原始数据集

### ISSUE THREAD

**Issue by lzl19971215** [HaoZhongkai/AS_Molecule#5]
您好，请问可否提供qm9_predata.py中所对应QM9的原始数据集下载链接？

**Comment by HaoZhongkai** [comment]
Hello,
&nbsp; You can find QM9 dataset in the following links,
&nbsp; &nbsp;http://quantum-machine.org/datasets/
&nbsp; &nbsp;https://figshare.com/collections/Quantum_chemistry_structures_and_properties_of_134_kilo_molecules/978904.


best,
Zhongkai Hao




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HaoZhongkai/AS_Molecule"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月19日(星期六) 中午11:48
收件人:&nbsp;"HaoZhongkai/AS_Molecule"<AS_Molecule@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HaoZhongkai/AS_Molecule] QM9原始数据集 (#5)





 
您好，请问可否提供qm9_predata.py中所对应QM9的原始数据集下载链接？

**Comment by lzl19971215** [comment]
thanks！
