### ISSUE TITLE
About check_point_test()

### ISSUE THREAD

**Issue by lzl19971215** [HaoZhongkai/AS_Molecule#6]
hello, thanks for your sharing! I have 2 following questions about your program :
1. How long will it probably take to `run_al.py` on qm9 datasets with default settings on 1 single tesla v100 gpu?
2. While running the `run_al.py` script, I meet following error:
`TypeError: check_point_test() missing 2 required positional arguments: 'max_epochs' and 'device'`
What is the functionality of `check_point_test`, can I just discard this step? if i can't, what should be the proper value of `max_epochs`?

Looking forward to your reply!

**Comment by HaoZhongkai** [comment]
Hello,
&nbsp; It takes less than 24 hours running run_al.py on qm9 dataset on one v100 gpu.
&nbsp; The check_point_test is for recording experimental data. You can omit this step if you do not want to record them.
Thanks!


best,
Zhongkai




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HaoZhongkai/AS_Molecule"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 中午1:39
收件人:&nbsp;"HaoZhongkai/AS_Molecule"<AS_Molecule@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HaoZhongkai/AS_Molecule] About check_point_test() (#6)





 
hello, thanks for your sharing! I have 2 following questions about your program :
  
How long will it probably take to run_al.py on qm9 datasets with default settings on 1 single tesla v100 gpu?
 
While running the run_al.py script, I meet following error:
 TypeError: check_point_test() missing 2 required positional arguments: 'max_epochs' and 'device'
 What is the functionality of check_point_test, can I just discard this step? if i can't, what should be the proper value of max_epochs?
  
Looking forward to your reply!

**Comment by lzl19971215** [comment]
Thanks, and what about  running `wsl_al.py` script, how long will it probably take?

**Comment by coderlemon17** [comment]
Do you have the answer?

**Comment by yingchengyang** [comment]
Great!
